@startuml

header "EFSS Screening Set"
 

title Enhancing FHIR for Social Services

class Individual {
 
}

 

ScreeningSet : identifier :Identifier
ScreeningSet : category : Code
ScreeningSet : type : Code
ScreeningSet : status : Code

class ScreeningSet {

}

 
  

ScreeningSet "0..*" - "1..1" Individual
(ScreeningSet, Individual) .. Membership

class Membership {
   membership : Code
   effectiveTime : Date
   status : Code
   role : Code
   verification : Code   
}
 


   
 
@enduml