@startuml

 

header "EFSS Life Set"

@startuml

title Enhancing FHIR for Social Services

class Individual {
 
}

 
 

class LifeSet {
    
+ individual : Individual
}

LifeSet : category : Code
LifeSet : type : Code
 

' Individual "*" <--o "0" LifeSet : association

' Individual "*" <--o "1" ScreeningGroup : member

   

 
 
LifeSet "0..*" - "1..1" Individual
(LifeSet, Individual) .. Association

class Association {
   type : Code
   effectiveTime : Date
   effectiveTiming : Timing
   status : Code
   verification : Code
   qualification : Code
}

LifeSet "0..*" - "1..1" Organization
(LifeSet, Organization) .. Association
 
LifeSet "0..*" - "1..1" LegalJurisdiction
(LifeSet, LegalJurisdiction) .. Association
 


   
 
@enduml
