@startuml
participant CareCoordinator as Foo
collections LifeSet as Foo6
collections ScreeningSet as Foo7

boundary    FHIR    as Foo3
participant ProgramSystem as Foo2
 

control     HUDCriteria     as Foo4

entity      Entity      as Foo4


 
Foo6 -> Foo : To review Life Set 
Foo -> Foo7 : To create Screening Set 
 
Foo -> Foo2 : To send Screening Set
Foo2 -> Foo4 : To evalute Screening Set
Foo4 -> Foo2 : To return Resulting  Set

Foo2 -> Foo : To return Resulting  Set

 
@enduml
